{
 "title": "Solar System Monitoring",
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  {
   "title": "Today's Energy Source",
   "type": "grafana-piechart-panel",
   "description": "Shows the amount and energy that comes from the grid and the sun.",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "alias": "Grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM sw_EnergyFromGridToday",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Solar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM sw_FromBatteryEnergyToday",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Inverter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Inverter Status",
   "type": "singlestat",
   "description": "Current status of the inverter",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 10 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM \"sw_inverterStatus\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC Frequency",
   "type": "singlestat",
   "description": "Grid input frequency",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM sw_AC1Frequency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DC Voltage",
   "type": "singlestat",
   "description": "Battery bank voltage, as seen by the inverter",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 13 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM sw_batteryVoltage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DC Current",
   "type": "singlestat",
   "description": "DC load (battery draw or charge), as seen by the inverter",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 13 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM sw_batteryCurrent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DC Input Power",
   "type": "singlestat",
   "description": "Battery bank power draw, as seen by the inverter",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 13 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM sw_invertDCPower",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC1 Voltage",
   "type": "singlestat",
   "description": "Grid voltage (L1 to L2)",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 16 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM sw_AC1Voltage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC1 Current",
   "type": "singlestat",
   "description": "Grid input current",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 16 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM sw_AC1InputCurrent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC1 Input Power",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 16 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM sw_AC1InputPower",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "L1 Voltage",
   "type": "singlestat",
   "description": "Line 1 voltage",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 19 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM sw_AC1L1Voltage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "L1 Current",
   "type": "singlestat",
   "description": "Line 1 current",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 19 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM sw_AC1L1Current",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "L2 Voltage",
   "type": "singlestat",
   "description": "Line 2 voltage",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 22 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM sw_AC1L2Voltage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "L2 Current",
   "type": "singlestat",
   "description": "Line 2 current",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 22 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM sw_AC1L2Current",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Solar Input", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Daily Solar Energy",
   "type": "singlestat",
   "description": "Energy harvested from the sun during so far during the day",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 26 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM \"kWhTbl\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Amps In",
   "type": "singlestat",
   "description": "Current provided by the solar panels",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 26 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM pvAmpsTbl",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Power In",
   "type": "singlestat",
   "description": "Power provided by the solar panels",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 26 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM wattsInTbl",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Voltage In",
   "type": "singlestat",
   "description": "Solar panels voltage",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 29 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM pvVoltsTbl",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Charger", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "State of Charge",
   "type": "singlestat",
   "description": "Status of the Midnite Classic 150 MPPT Charger",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM \"stateOfChargeTbl\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Charging Current",
   "type": "singlestat",
   "description": "Current at which the batteries are being charged",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 36 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM batAmpsTbl",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shunt Amps",
   "type": "singlestat",
   "description": "Current draw from/to the batteries by the inverter.\nPositive current: Battery is being charged by the inverter.\nNegative current: Power is being drawn from battery.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 36 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM \"whzAmpsTbl\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Temp",
   "type": "singlestat",
   "description": "Battery bank temperarure",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 39 },
   "format": "farenheit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM batteryTemp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FET Temp",
   "type": "singlestat",
   "description": "Field-Effect Transistor temperature",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 39 },
   "format": "farenheit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM fetTemp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PCB Temp",
   "type": "singlestat",
   "description": "Board temperature",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 39 },
   "format": "farenheit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM pcbTemp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "description": "Plot of power produced and consumed vs time, as seen by the load controller",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "watt", "label": "Power" }
   ],
   "targets": [
    {
     "alias": "Power Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM \"wattsInTbl\" WHERE value < 10000",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Power Consumed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM \"consumedWattsTbl\" WHERE value < 10000",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Battery Bank", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Battery Voltage",
   "type": "singlestat",
   "description": "Battery bank voltage, as seen by the load controller",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 49 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM batVoltsTbl",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery SOC%",
   "type": "singlestat",
   "description": "Estimated battery bank state of charge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 49 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM \"socTbl\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Remaining Battery Capacity",
   "type": "singlestat",
   "description": "Estimated battery bank remaining capacity",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(value) FROM \"remainingAhTbl\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "graph",
   "description": "Battery bank voltage and state of charge vs time",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "volt", "label": "Voltage" }
   ],
   "targets": [
    {
     "alias": "Battery Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM \"batVoltsTbl\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "SOC %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM \"socTbl\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}